<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KomangRaim Laode342</name>
   <tag></tag>
   <elementGuidId>516a28d0-ea75-4cc5-a71b-a11ac6007a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.h4HgbO_Uu1JYg5UGANeQ.wTUruPetkKdWAR1dd6w4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchPage']/div/div/section[2]/div[2]/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>tracklist-row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h4HgbO_Uu1JYg5UGANeQ wTUruPetkKdWAR1dd6w4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KomangRaim Laode3:42</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchPage&quot;)/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E khkfPsJuVBQyL_5cLT7y&quot;]/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E nGARy02O1AklvHT7OBLA&quot;]/section[@class=&quot;QVIrLvegL13F9cEdMqfT EbZrO5qZMclA_AaI3NV8&quot;]/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E&quot;]/div[@class=&quot;Lj3brgOJmjcq6MQ22XKq&quot;]/div[@class=&quot;ShMHCGsT93epRGdxJp2w&quot;]/div[@class=&quot;JUa6JJNj7R_Y3i4P8YUX&quot;]/div[2]/div[1]/div[@class=&quot;h4HgbO_Uu1JYg5UGANeQ wTUruPetkKdWAR1dd6w4&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchPage']/div/div/section[2]/div[2]/div/div/div/div[2]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Songs'])[2]/following::div[16]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Song'])[1]/following::div[22]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[2]/div/div/div/div[2]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KomangRaim Laode3:42' or . = 'KomangRaim Laode3:42')]</value>
   </webElementXpaths>
</WebElementEntity>
